Repository yju-FukuFuku/FukuFuku_Frontend_Refactoring-repo, pull requests merged in 2023-10, with the labels that each got.

#52 refactor(MyPage): Refactor nickName update feature, introduction update feature
  src/api/Image.ts
  src/api/User.ts
  src/api/index.ts
  src/components/Nav.tsx
  src/pages/MyPage/index.tsx
  src/store/Auth.ts
Labels: front

#53 feat(MyPage): Add fire function for displaying alerts
  src/api/BoardAPI.ts
  src/api/Image.ts
  src/components/Nav.tsx
  src/components/board.tsx
  src/pages/BoardPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/myPage.module.css
  src/pages/WritePage/index.tsx
  src/util/fire.ts
Labels: front

#54 Fix: Nav 넓이 Board에 맞춤
  src/components/Category.tsx
  src/components/Nav.tsx
Labels: front

#56 Style 수정 (메인 페이지, 글 작성 페이지)
  src/components/Category.tsx
  src/components/Nav.tsx
  src/components/board.tsx
  src/pages/WritePage/index.tsx
Labels: front

#55 feat: 특정 유저 글 불러오기 기능 추가
  src/App.tsx
  src/api/BoardAPI.ts
  src/api/User.ts
  src/components/Nav.tsx
  src/components/Specific.tsx
  src/pages/HomePage/index.tsx
  src/pages/MyPage/Setting.tsx
  src/pages/MyPage/WriteList.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/myPage.module.css
  src/pages/WriteListPage/index.tsx
Labels: front

#58 feat: 검색 기능 추가
  src/components/Specific.tsx
  src/pages/MyPage/WriteList.tsx
  src/pages/MyPage/myPage.module.css
  src/pages/WriteListPage/index.tsx
Labels: 📬 API

#59 Fix: 무한 스크롤 수정 (백앤드 수정 후 test 필요) 외 1개 커밋
  src/pages/BoardPage/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/SearchPage/index.tsx
Labels: 🐞 BugFix, 🎨 Html&css

#61 게시글 작성 방법 수정, 타입들 지정, 태그 검색페이지 수정
  src/App.tsx
  src/api/BoardAPI.ts
  src/api/Comments.ts
  src/api/Image.ts
  src/api/Login.ts
  src/api/index.ts
  src/components/Category.tsx
  src/components/Comment/Comment.tsx
  src/components/Comment/ReComment.tsx
  src/components/Nav.tsx
  src/components/board.tsx
  src/hooks/useImage.tsx
  src/main.tsx
  src/pages/BoardPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/TagPage/index.tsx
  src/pages/WriteListPage/index.tsx
  src/pages/WritePage/index.tsx
  src/store/Auth.ts
  src/store/User.ts
  src/store/index.ts
  src/types/BoardType.ts
  src/types/SearchType.ts
  src/types/UserType.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#62 refact: mypage-navbar css modify & add searchBoard api
  src/api/BoardAPI.ts
  src/components/Specific.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/myPage.module.css
  src/pages/WriteListPage/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#63 Fix : 무한 스크롤 수정했습니다.
  src/api/BoardAPI.ts
  src/pages/HomePage/index.tsx
Labels: 🐞 BugFix

#67 fix(api): Fix session expiration handling
  src/App.tsx
  src/api/index.ts
  src/components/Nav.tsx
  src/pages/MyPage/Setting.tsx
  src/pages/MyPage/index.tsx
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#68 refactor: Refactor request to include ID of last retrieved post
  src/api/BoardAPI.ts
  src/pages/HomePage/index.tsx
Labels: 🔨 Refactor, 📬 API

#70 fix(TagPage): fix null check in summary function
  src/pages/BoardPage/index.tsx
  src/pages/TagPage/index.tsx
Labels: 🐞 BugFix

#72 이미지 관련 기능 추가, 토큰 버그 수정
  README.md
  package.json
  src/api/index.ts
  src/components/Loading.tsx
  src/hooks/useImageCompression.tsx
  src/pages/WritePage/index.tsx
  yarn.lock
Labels: ✨ Feature, 🐞 BugFix

#73 Feat: Board 카드에 좋아요 개수 표시 등 2개 커밋
  src/api/BoardAPI.ts
  src/components/board.tsx
  src/pages/HomePage/index.tsx
Labels: ✨ Feature

#76 feat : add function imageSrc
  .gitignore
  package-lock.json
  src/api/BoardAPI.ts
  src/components/ImageParser.tsx
  src/components/Nav.tsx
  src/components/Specific.tsx
  src/components/board.tsx
  src/index.css
  src/pages/MyPage/WriteList.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/myPage.module.css
  src/pages/SearchPage/index.tsx
  src/pages/WriteListPage/index.tsx
  src/types/BoardType.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#78 refact: modify Link&scroll
  src/components/ImageParser.tsx
  src/components/Specific.tsx
  src/pages/MyPage/WriteList.tsx
  src/pages/MyPage/myPage.module.css
  src/pages/SearchPage/index.tsx
Labels: 🔨 Refactor

#79 버그 수정, 리드미 추가
  README.md
  src/api/Comments.ts
  src/components/Comment/Comment.tsx
  src/components/Comment/ReComment.tsx
  src/components/Comment/comment.module.scss
  src/pages/BoardPage/index.tsx
  src/pages/WritePage/index.tsx
  src/types/CommentType.ts
Labels: 📃 Docs, 🐞 BugFix
